version: "3"

services:
  database:
    image: powertic/percona-docker
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    restart: always
    networks:
      - mauticnet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""

  mautic:
    container_name: mautic
    image: mautic-3.0
    volumes:
      - mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=database
      - MAUTIC_DB_USER=mauticuser
      - MAUTIC_DB_PASSWORD=123456
      - MAUTIC_DB_NAME=mautic
      - MYSQL_ROOT_PASSWORD=
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    restart: always
    networks:
      - mauticnet
    ports:
      - "8880:80"
